### ISSUE TITLE
AssertionError with privates

### ISSUE THREAD

**Issue by jonpas** [LordGolias/sqf#1]
```
Traceback (most recent call last):
  File "sqflintace.py", line 37, in <module>
    analyze(f.read(), writer)
  File "sqflintace.py", line 14, in analyze
    exceptions = sqf.analyser.analyze(result).exceptions
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 354, in analyze
    analyzer.execute_code(file, extra_scope={'_this': arg})
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 128, in execute_code
    outcome = super().execute_code(code, params, extra_scope)
  File "/usr/local/lib/python3.5/dist-packages/sqf/base_interpreter.py", line 128, in execute_code
    outcome = self.execute_single(statement)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 211, in execute_single
    t = self.execute_token(token)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 92, in execute_token
    result = self.execute_single(statement=token)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 211, in execute_single
    t = self.execute_token(token)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 92, in execute_token
    result = self.execute_single(statement=token)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 212, in execute_single
    v = self.value(t)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 74, in value
    result = self.execute_code_lazy(token)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 114, in execute_code_lazy
    outcome = analyser.execute_code(code, params, extra_scope)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 128, in execute_code
    outcome = super().execute_code(code, params, extra_scope)
  File "/usr/local/lib/python3.5/dist-packages/sqf/base_interpreter.py", line 128, in execute_code
    outcome = self.execute_single(statement)
  File "/usr/local/lib/python3.5/dist-packages/sqf/analyser.py", line 170, in execute_single
    self.add_privates(self.value(rhs))
  File "/usr/local/lib/python3.5/dist-packages/sqf/base_interpreter.py", line 109, in add_privates
    assert(isinstance(variable, String))
AssertionError
```
On file: https://github.com/acemod/ACE3/blob/3f4564605beeb8cfb6f3a253000fd65eee47a812/addons/atragmx/functions/fnc_update_truing_drop_selection.sqf

**Comment by LordGolias** [comment]
I think this was solved by a more recent version as I am not being able to reproduce it in the latest commit, 0b952c1. Can you try in this or subsequent commits?

**Comment by jonpas** [comment]
Seems to be due to doing it recursively, need to implement native way of doing that.

**Comment by jonpas** [comment]
This doesn't happen anymore after mentioned commit.
