### ISSUE TITLE
Column start greater than line length

### ISSUE THREAD

**Issue by DAmNRelentless** [LordGolias/sqf#24]
Running into that issue when opening the server_functions.sqf on vanilla epoch 1.0.6.1 files. It's definitly working tho. Attached is the error log + the .sqf file that was mentioned that triggers this error.
[error files.zip](https://github.com/LordGolias/sqf/files/1307741/error.files.zip)

**Comment by dedmen** [comment]
Same.
https://github.com/acemod/ACE3/blob/c9ad92e92d26f929e3cb78a53743585e5ffa20d8/addons/medical_damage/functions/fnc_woundsHandler.sqf

```
C:\Users\XXX\.atom\packages\linter\lib\linter-registry.js:159 [Linter] Error running SQFlint Error: Column start (80) greater than line length (32) for line 6
    at Object.generateRange (C:\Users\XXX\.atom\packages\linter-sqf\node_modules\atom-linter\lib\index.js:181:11)
    at file:///C:/Users/XXX/.atom/packages/linter-sqf/lib/init.js:105:50
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(anonymous) @ C:\Users\XXX\.atom\packages\linter\lib\linter-registry.js:159
```

**Comment by NemesisRE** [comment]
Same here
https://github.com/quies-in-proelium/qiptpl/blob/bft/addons/bft/functions/fnc_iconUnits.sqf
```
C:\Users\USER\.atom\packages\linter\lib\linter-registry.js:155 [Linter] Error running SQFlint Error: Column start (82) greater than line length (81) for line 58
    at Object.generateRange (C:\Users\USER\.atom\packages\linter-puppet-lint\node_modules\atom-linter\lib\index.js:181:11)
    at file:///C:/Users/USER/.atom/packages/linter-sqf/lib/init.js:105:50
    at process._tickCallback (internal/process/next_tick.js:68:7)
(anonymous) @ C:\Users\USER\.atom\packages\linter\lib\linter-registry.js:155
```
