### ISSUE TITLE
I don't get where i'm failing!

### ISSUE THREAD

**Issue by iDanny1212** [LordGolias/sqf#27]
```
C:\Users\danny\.atom\packages\linter\lib\linter-registry.js:159 [Linter] Error running SQFlint Error: "C:UsersdannyAppDataLocalProgramsPythonPython36Scriptssqflint.exe" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
    at ChildProcess.<anonymous> (C:\Users\danny\.atom\packages\linter-sqf-master\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
(anonymous) @ C:\Users\danny\.atom\packages\linter\lib\linter-registry.js:159
```
I get this error on Atom Startup.

Can someone help me, please?

**Comment by iDanny1212** [comment]
Resolved, sorry for that 👍
