### ISSUE TITLE
Error running SQFlint

### ISSUE THREAD

**Issue by Zantza** [LordGolias/sqf#36]
Hey, I've been trying to get this working for a while now. Installed it just as the instructions say, but I keep getting an error from it. When I try to save an .sqf file, it says "[Linter] Error Running SQFLint.
This is what I found in the developer tools:

`[Linter] Error running SQFlint Error: Traceback (most recent call last):
  File "c:\users\niko\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\niko\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Niko\AppData\Local\Programs\Python\Python37-32\Scripts\sqflint.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'sqflint'
    at ChildProcess.<anonymous> (C:\Users\Niko\.atom\packages\linter-sqf\node_modules\sb-exec\lib\index.js:56)
    at emitTwo (events.js:126)
    at ChildProcess.emit (events.js:214)
    at maybeClose (internal/child_process.js:925)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209)`

Any ideas? Would love to get this working.

**Comment by LordGolias** [comment]
1. Could you describe exactly what you did? (e.g. installed sqf via pip or downloaded from github? which commands you used to install sqflint?)
2. Windows or unix?
3. Can you try to run sqflint in the powershell?

It seems that the the script `sqflint.exe` is not finding `sqflint`. This is odd and hints at an installation problem.
