### ISSUE TITLE
Empty [] checks return error

### ISSUE THREAD

**Issue by OfficialNoms** [LordGolias/sqf#38]
`My_Variable = [];`

returns 

```[Linter] Error running SQFlint Error: Traceback (most recent call last):
  File "d:\sqflint\sqf\types.py", line 223, in _with_commas
    yield next(it)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python37-32\Scripts\sqflint-script.py", line 11, in <module>
    load_entry_point('sqflint', 'console_scripts', 'sqflint')()
  File "D:\sqflint\sqflint.py", line 112, in _main
    return main(sys.argv[1:])
  File "D:\sqflint\sqflint.py", line 90, in main
    analyze(code, writer, exceptions_list)
  File "D:\sqflint\sqflint.py", line 20, in analyze
    result = parse(code)
  File "d:\sqflint\sqf\parser.py", line 574, in parse
    result = parse_block(tokens + [EndOfFile()], _analyze_tokens)[0]
  File "d:\sqflint\sqf\parser.py", line 486, in parse_block
    expression, size = parse_block(all_tokens, analyze_tokens, i + 1, lvls, stop_statement, defines=defines)
  File "d:\sqflint\sqf\parser.py", line 474, in parse_block
    expression, size = parse_block(all_tokens, analyze_tokens, i + 1, lvls, stop_statement='single', defines=defines)
  File "d:\sqflint\sqf\parser.py", line 502, in parse_block
    return Array(_analyze_array(tokens, analyze_tokens, all_tokens[:i])), i - start
  File "d:\sqflint\sqf\types.py", line 214, in __init__
    self.update_tokens()
  File "d:\sqflint\sqf\types.py", line 217, in update_tokens
    self._tokens = [ParserKeyword('[')] + list(self._with_commas()) + [ParserKeyword(']')]
RuntimeError: generator raised StopIteration
    at ChildProcess.<anonymous> (C:\Users\aaron\.atom\packages\linter-sqf\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)```

**Comment by LordGolias** [comment]
I cannot reproduce this in Python 3.7, but there seems to have been a change in API of generators from 3.0 to 3.7, therefore, I am fixing this to maintain backward compatibility with older versions of Python. Could you check that [this branch](https://github.com/LordGolias/sqf/tree/issue38) fixes the issue?
